### ISSUE TITLE
Making http calls on Mac OSX

### ISSUE THREAD

**Issue by jtibrewala** [ThePromptIndex/ExcelAI#1]
What is the equivalent of CreateObject("MSXML2.XMLHTTP") to call an http request from vba in excel on MacOSX?  This code only works on Windows and is not Mac compatible.

**Comment by ThePromptIndex** [comment]
You can make HTTP requests from VBA in Excel on macOS using AppleScript.

Create an AppleScript to make the HTTP request: Save the following AppleScript as HTTPRequest.scpt using the Script Editor. 

 on run {url} 
 set curlCommand to "curl -s " & url 
 set response to do shell script curlCommand
 return response 
end run

Then  Call the AppleScript from VBA: Use the MacScript function to call this AppleScript from your VBA code
